import React from 'react';
import {createRoot} from 'react-dom/client';
import {createClient} from '@supabase/supabase-js';
import * as pdfjs from 'pdfjs-dist';
import workerUrl from 'pdfjs-dist/build/pdf.worker.min.mjs?url';
import './styles.css';
import React from 'react';
import {createRoot} from 'react-dom/client';
import {createClient} from '@supabase/supabase-js';
import * as pdfjs from 'pdfjs-dist';
import workerUrl from 'pdfjs-dist/build/pdf.worker.min.mjs?url';
import './styles.css';

pdfjs.GlobalWorkerOptions.workerSrc=workerUrl;
const supabase=createClient(import.meta.env.VITE_SUPABASE_URL,import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY);
const letters=['A','B','C','D','E'];
const normalize=t=>(t||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\b\d+\b/g,' ').replace(/[^a-z0-9\s]/g,' ').replace(/\s+/g,' ').trim();
const similarity=(a,b)=>{const A=new Set(normalize(a).split(' ').filter(x=>x.length>2)),B=new Set(normalize(b).split(' ').filter(x=>x.length>2));if(!A.size||!B.size)return 0;let n=0;A.forEach(x=>B.has(x)&&n++);return 2*n/(A.size+B.size)};
function parseQuestions(text){const clean=text.replace(/\r/g,'').trim(),marks=[...clean.matchAll(/(?:^|\n)\s*(\d{1,3})(?:\s*[.)º°-]\s*|\s*\n\s*)/g)];return marks.map((m,i)=>{const block=clean.slice(m.index+m[0].length,i+1<marks.length?marks[i+1].index:clean.length).trim(),am=[...block.matchAll(/(?:^|\n|\s)(?:\(\s*([A-E])\s*\)|([A-E])\s*[).:-])\s+/g)];if(am.length<2)return null;return {tempId:crypto.randomUUID(),original_number:+m[1],statement:block.slice(0,am[0].index).trim(),alternatives:am.map((x,j)=>({letter:x[1]||x[2],text:block.slice(x.index+x[0].length,j+1<am.length?am[j+1].index:block.length).trim()})),correct_option:'',discipline:'',subject:'',explanation:''}}).filter(Boolean)}

function App(){
 const [session,setSession]=React.useState(undefined),[tab,setTab]=React.useState('cadastro'),[questions,setQuestions]=React.useState([]),[drafts,setDrafts]=React.useState([]),[raw,setRaw]=React.useState(''),[notice,setNotice]=React.useState(''),[busy,setBusy]=React.useState(false);
 React.useEffect(()=>{supabase.auth.getSession().then(({data})=>setSession(data.session));const {data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return ()=>data.subscription.unsubscribe()},[]);
 const load=React.useCallback(async()=>{if(!session)return;const {data,error}=await supabase.from('questions').select('*').order('created_at',{ascending:false});if(error)setNotice(error.message);else setQuestions(data||[])},[session]);
 React.useEffect(()=>{load()},[load]);
 if(session===undefined)return <div className="center">Carregando…</div>;
 if(!session)return <Auth/>;
 async function readPdf(file){setBusy(true);setNotice('Lendo PDF…');try{const pdf=await pdfjs.getDocument({data:await file.arrayBuffer()}).promise;let all='';for(let p=1;p<=pdf.numPages;p++){const page=await pdf.getPage(p),content=await page.getTextContent();all+=content.items.map(x=>x.str+(x.hasEOL?'\n':' ')).join('')+'\n'}setRaw(all);setNotice(`${pdf.numPages} página(s) lida(s). Clique em Separar questões.`)}catch(e){setNotice('Não foi possível ler o PDF: '+e.message)}finally{setBusy(false)}}
 function process(){const q=parseQuestions(raw);setDrafts(q);setNotice(q.length?`${q.length} questão(ões) identificadas.`:'Nenhuma questão foi identificada. Confira a numeração e as alternativas.')}
 async function save(q,force=false){if(!q.correct_option)return setNotice('Selecione o gabarito antes de salvar.');const hit=questions.map(x=>({x,s:similarity(q.statement,x.statement)})).sort((a,b)=>b.s-a.s)[0];if(hit?.s>=.62&&!force&&!confirm(`Possível duplicidade (${Math.round(hit.s*100)}% semelhante):\n\n${hit.x.statement}\n\nDeseja salvar mesmo assim?`))return;const payload={user_id:session.user.id,statement:q.statement,alternatives:q.alternatives,correct_option:q.correct_option,discipline:q.discipline||null,subject:q.subject||null,explanation:q.explanation||null,normalized_statement:normalize(q.statement),original_number:q.original_number||null};const {error}=await supabase.from('questions').insert(payload);if(error)setNotice(error.message);else{setDrafts(d=>d.filter(x=>x.tempId!==q.tempId));setNotice('Questão salva.');load()}}
 async function remove(id){if(!confirm('Excluir esta questão?'))return;const {error}=await supabase.from('questions').delete().eq('id',id);if(error)setNotice(error.message);else load()}
 return <main><header><div><h1>Caderno de Questões</h1><small>{session.user.email}</small></div><button className="light" onClick={()=>supabase.auth.signOut()}>Sair</button></header><nav>{[['cadastro','Cadastro'],['questoes',`Questões (${questions.length})`],['estudos','Estudos']].map(([id,l])=><button className={tab===id?'active':''} onClick={()=>setTab(id)} key={id}>{l}</button>)}</nav>{notice&&<div className="notice">{notice}<button onClick={()=>setNotice('')}>×</button></div>}
 {tab==='cadastro'&&<section><div className="card"><h2>Importar prova</h2><p>O PDF é lido no navegador e não é armazenado.</p><label className="drop">{busy?'Processando…':'Selecionar PDF'}<input hidden type="file" accept="application/pdf" onChange={e=>e.target.files[0]&&readPdf(e.target.files[0])}/></label><div className="sep">ou cole o texto</div><textarea rows="9" value={raw} onChange={e=>setRaw(e.target.value)} placeholder={'1. Enunciado…\nA) Alternativa…'}/><button onClick={process}>Separar questões</button></div>{drafts.map((q,i)=><Editor key={q.tempId} q={q} index={i} setDrafts={setDrafts} save={save}/>)}</section>}
 {tab==='questoes'&&<section className="card"><h2>Questões cadastradas</h2>{!questions.length?<p>Nenhuma questão cadastrada.</p>:questions.map((q,i)=><article className="item" key={q.id}><div><b>{i+1}. {q.statement}</b><small>{q.discipline||'Sem disciplina'} · {q.subject||'Sem assunto'} · Gabarito {q.correct_option}</small></div><button className="danger" onClick={()=>remove(q.id)}>Excluir</button></article>)}</section>}
 {tab==='estudos'&&<Study questions={questions} supabase={supabase} userId={session.user.id}/>}</main>
}

function Auth(){const [email,setEmail]=React.useState(''),[password,setPassword]=React.useState(''),[msg,setMsg]=React.useState(''),[busy,setBusy]=React.useState(false);async function act(kind){setBusy(true);const {error}=kind==='login'?await supabase.auth.signInWithPassword({email,password}):await supabase.auth.signUp({email,password});setMsg(error?error.message:kind==='login'?'Login realizado.':'Cadastro realizado. Confira seu e-mail se a confirmação estiver ativada.');setBusy(false)}return <div className="auth card"><h1>Caderno de Questões</h1><p>Entre ou crie sua conta.</p><input type="email" placeholder="E-mail" value={email} onChange={e=>setEmail(e.target.value)}/><input type="password" placeholder="Senha" value={password} onChange={e=>setPassword(e.target.value)}/><button disabled={busy} onClick={()=>act('login')}>Entrar</button><button className="light" disabled={busy} onClick={()=>act('signup')}>Criar conta</button>{msg&&<p>{msg}</p>}</div>}
function Editor({q,index,setDrafts,save}){const patch=(key,value)=>setDrafts(ds=>ds.map(x=>x.tempId===q.tempId?{...x,[key]:value}:x));const alt=(letter,text)=>patch('alternatives',q.alternatives.map(a=>a.letter===letter?{...a,text}:a));return <article className="card editor"><h3>Questão {q.original_number||index+1}</h3><textarea rows="4" value={q.statement} onChange={e=>patch('statement',e.target.value)}/>{q.alternatives.map(a=><label className="alt" key={a.letter}><input type="radio" name={q.tempId} checked={q.correct_option===a.letter} onChange={()=>patch('correct_option',a.letter)}/><b>{a.letter}</b><input value={a.text} onChange={e=>alt(a.letter,e.target.value)}/></label>)}<div className="cols"><input placeholder="Disciplina" value={q.discipline} onChange={e=>patch('discipline',e.target.value)}/><input placeholder="Assunto" value={q.subject} onChange={e=>patch('subject',e.target.value)}/></div><textarea rows="2" placeholder="Comentário (opcional)" value={q.explanation} onChange={e=>patch('explanation',e.target.value)}/><button onClick={()=>save(q)}>Salvar questão</button></article>}
function Study({questions,supabase,userId}){const [discipline,setDiscipline]=React.useState(''),[subject,setSubject]=React.useState(''),[pos,setPos]=React.useState(0),[choice,setChoice]=React.useState(''),[checked,setChecked]=React.useState(false);const list=questions.filter(q=>(!discipline||q.discipline===discipline)&&(!subject||q.subject===subject)),q=list[pos];const reset=()=>{setPos(0);setChoice('');setChecked(false)};async function correct(){setChecked(true);await supabase.from('answers').insert({user_id:userId,question_id:q.id,selected_option:choice,is_correct:choice===q.correct_option})}if(!questions.length)return <section className="card"><p>Cadastre questões para começar.</p></section>;return <section className="card study"><div className="cols"><select value={discipline} onChange={e=>{setDiscipline(e.target.value);reset()}}><option value="">Todas as disciplinas</option>{[...new Set(questions.map(x=>x.discipline).filter(Boolean))].map(x=><option key={x}>{x}</option>)}</select><select value={subject} onChange={e=>{setSubject(e.target.value);reset()}}><option value="">Todos os assuntos</option>{[...new Set(questions.map(x=>x.subject).filter(Boolean))].map(x=><option key={x}>{x}</option>)}</select></div>{!q?<p>Nenhuma questão encontrada.</p>:<><small>Questão {pos+1} de {list.length}</small><h2>{q.statement}</h2>{q.alternatives.map(a=><button key={a.letter} className={`option ${choice===a.letter?'chosen':''} ${checked&&a.letter===q.correct_option?'correct':''} ${checked&&choice===a.letter&&choice!==q.correct_option?'wrong':''}`} disabled={checked} onClick={()=>setChoice(a.letter)}><b>{a.letter}</b>{a.text}</button>)}{checked&&<div className={choice===q.correct_option?'result ok':'result no'}>{choice===q.correct_option?'Resposta correta!':`Resposta incorreta. Gabarito: ${q.correct_option}.`}{q.explanation&&<small>{q.explanation}</small>}</div>}<button disabled={!choice} onClick={checked?()=>{setPos((pos+1)%list.length);setChoice('');setChecked(false)}:correct}>{checked?'Próxima':'Corrigir'}</button></>}</section>}
createRoot(document.getElementById('root')).render(<App/>);
).then(({data})=>setSession(data.session));const {data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return ()=>data.subscription.unsubscribe()},[]);
 const load=React.useCallback(async()=>{if(!session)return;const {data,error}=await supabase.from('questions').select('*').order('created_at',{ascending:false});if(error)setNotice(error.message);else setQuestions(data||[])},[session]);
 React.useEffect(()=>{load()},[load]);
 if(session===undefined)return <div className="center">Carregando…</div>;
 if(!session)return <Auth/>;
 async function readPdf(file){setBusy(true);setNotice('Lendo PDF…');try{const pdf=await pdfjs.getDocument({data:await file.arrayBuffer()}).promise;let all='';for(let p=1;p<=pdf.numPages;p++){const page=await pdf.getPage(p),content=await page.getTextContent();all+=content.items.map(x=>x.str+(x.hasEOL?'\n':' ')).join('')+'\n'}setRaw(all);setNotice(`${pdf.numPages} página(s) lida(s). Clique em Separar questões.`)}catch(e){setNotice('Não foi possível ler o PDF: '+e.message)}finally{setBusy(false)}}
 function process(){const q=parseQuestions(raw);setDrafts(q);setNotice(q.length?`${q.length} questão(ões) identificadas.`:'Nenhuma questão foi identificada. Confira a numeração e as alternativas.')}
 async function save(q,force=false){if(!q.correct_option)return setNotice('Selecione o gabarito antes de salvar.');const hit=questions.map(x=>({x,s:similarity(q.statement,x.statement)})).sort((a,b)=>b.s-a.s)[0];if(hit?.s>=.62&&!force&&!confirm(`Possível duplicidade (${Math.round(hit.s*100)}% semelhante):\n\n${hit.x.statement}\n\nDeseja salvar mesmo assim?`))return;const payload={user_id:session.user.id,statement:q.statement,alternatives:q.alternatives,correct_option:q.correct_option,discipline:q.discipline||null,subject:q.subject||null,explanation:q.explanation||null,normalized_statement:normalize(q.statement),original_number:q.original_number||null};const {error}=await supabase.from('questions').insert(payload);if(error)setNotice(error.message);else{setDrafts(d=>d.filter(x=>x.tempId!==q.tempId));setNotice('Questão salva.');load()}}
 async function remove(id){if(!confirm('Excluir esta questão?'))return;const {error}=await supabase.from('questions').delete().eq('id',id);if(error)setNotice(error.message);else load()}
 return <main><header><div><h1>Caderno de Questões</h1><small>{session.user.email}</small></div><button className="light" onClick={()=>supabase.auth.signOut()}>Sair</button></header><nav>{[['cadastro','Cadastro'],['questoes',`Questões (${questions.length})`],['estudos','Estudos']].map(([id,l])=><button className={tab===id?'active':''} onClick={()=>setTab(id)} key={id}>{l}</button>)}</nav>{notice&&<div className="notice">{notice}<button onClick={()=>setNotice('')}>×</button></div>}
 {tab==='cadastro'&&<section><div className="card"><h2>Importar prova</h2><p>O PDF é lido no navegador e não é armazenado.</p><label className="drop">{busy?'Processando…':'Selecionar PDF'}<input hidden type="file" accept="application/pdf" onChange={e=>e.target.files[0]&&readPdf(e.target.files[0])}/></label><div className="sep">ou cole o texto</div><textarea rows="9" value={raw} onChange={e=>setRaw(e.target.value)} placeholder={'1. Enunciado…\nA) Alternativa…'}/><button onClick={process}>Separar questões</button></div>{drafts.map((q,i)=><Editor key={q.tempId} q={q} index={i} setDrafts={setDrafts} save={save}/>)}</section>}
 {tab==='questoes'&&<section className="card"><h2>Questões cadastradas</h2>{!questions.length?<p>Nenhuma questão cadastrada.</p>:questions.map((q,i)=><article className="item" key={q.id}><div><b>{i+1}. {q.statement}</b><small>{q.discipline||'Sem disciplina'} · {q.subject||'Sem assunto'} · Gabarito {q.correct_option}</small></div><button className="danger" onClick={()=>remove(q.id)}>Excluir</button></article>)}</section>}
 {tab==='estudos'&&<Study questions={questions} supabase={supabase} userId={session.user.id}/>}</main>
}

function Auth(){const [email,setEmail]=React.useState(''),[password,setPassword]=React.useState(''),[msg,setMsg]=React.useState(''),[busy,setBusy]=React.useState(false);async function act(kind){setBusy(true);const {error}=kind==='login'?await supabase.auth.signInWithPassword({email,password}):await supabase.auth.signUp({email,password});setMsg(error?error.message:kind==='login'?'Login realizado.':'Cadastro realizado. Confira seu e-mail se a confirmação estiver ativada.');setBusy(false)}return <div className="auth card"><h1>Caderno de Questões</h1><p>Entre ou crie sua conta.</p><input type="email" placeholder="E-mail" value={email} onChange={e=>setEmail(e.target.value)}/><input type="password" placeholder="Senha" value={password} onChange={e=>setPassword(e.target.value)}/><button disabled={busy} onClick={()=>act('login')}>Entrar</button><button className="light" disabled={busy} onClick={()=>act('signup')}>Criar conta</button>{msg&&<p>{msg}</p>}</div>}
function Editor({q,index,setDrafts,save}){const patch=(key,value)=>setDrafts(ds=>ds.map(x=>x.tempId===q.tempId?{...x,[key]:value}:x));const alt=(letter,text)=>patch('alternatives',q.alternatives.map(a=>a.letter===letter?{...a,text}:a));return <article className="card editor"><h3>Questão {q.original_number||index+1}</h3><textarea rows="4" value={q.statement} onChange={e=>patch('statement',e.target.value)}/>{q.alternatives.map(a=><label className="alt" key={a.letter}><input type="radio" name={q.tempId} checked={q.correct_option===a.letter} onChange={()=>patch('correct_option',a.letter)}/><b>{a.letter}</b><input value={a.text} onChange={e=>alt(a.letter,e.target.value)}/></label>)}<div className="cols"><input placeholder="Disciplina" value={q.discipline} onChange={e=>patch('discipline',e.target.value)}/><input placeholder="Assunto" value={q.subject} onChange={e=>patch('subject',e.target.value)}/></div><textarea rows="2" placeholder="Comentário (opcional)" value={q.explanation} onChange={e=>patch('explanation',e.target.value)}/><button onClick={()=>save(q)}>Salvar questão</button></article>}
function Study({questions,supabase,userId}){const [discipline,setDiscipline]=React.useState(''),[subject,setSubject]=React.useState(''),[pos,setPos]=React.useState(0),[choice,setChoice]=React.useState(''),[checked,setChecked]=React.useState(false);const list=questions.filter(q=>(!discipline||q.discipline===discipline)&&(!subject||q.subject===subject)),q=list[pos];const reset=()=>{setPos(0);setChoice('');setChecked(false)};async function correct(){setChecked(true);await supabase.from('answers').insert({user_id:userId,question_id:q.id,selected_option:choice,is_correct:choice===q.correct_option})}if(!questions.length)return <section className="card"><p>Cadastre questões para começar.</p></section>;return <section className="card study"><div className="cols"><select value={discipline} onChange={e=>{setDiscipline(e.target.value);reset()}}><option value="">Todas as disciplinas</option>{[...new Set(questions.map(x=>x.discipline).filter(Boolean))].map(x=><option key={x}>{x}</option>)}</select><select value={subject} onChange={e=>{setSubject(e.target.value);reset()}}><option value="">Todos os assuntos</option>{[...new Set(questions.map(x=>x.subject).filter(Boolean))].map(x=><option key={x}>{x}</option>)}</select></div>{!q?<p>Nenhuma questão encontrada.</p>:<><small>Questão {pos+1} de {list.length}</small><h2>{q.statement}</h2>{q.alternatives.map(a=><button key={a.letter} className={`option ${choice===a.letter?'chosen':''} ${checked&&a.letter===q.correct_option?'correct':''} ${checked&&choice===a.letter&&choice!==q.correct_option?'wrong':''}`} disabled={checked} onClick={()=>setChoice(a.letter)}><b>{a.letter}</b>{a.text}</button>)}{checked&&<div className={choice===q.correct_option?'result ok':'result no'}>{choice===q.correct_option?'Resposta correta!':`Resposta incorreta. Gabarito: ${q.correct_option}.`}{q.explanation&&<small>{q.explanation}</small>}</div>}<button disabled={!choice} onClick={checked?()=>{setPos((pos+1)%list.length);setChoice('');setChecked(false)}:correct}>{checked?'Próxima':'Corrigir'}</button></>}</section>}
createRoot(document.getElementById('root')).render(<App/>);
